apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: "nfs-client"
