apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube
  labels:
    app: youtube
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
        - name: youtube
          image: ghcr.io/ddung1203/youtube-reloaded:2
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: youtube-persistent-storage
              mountPath: /app/uploads
          envFrom:
            - secretRef:
                name: mydata
          resources:
            requests:
              cpu: "0.5"
              memory: "1G"
            limits:
              cpu: "0.5"
              memory: "1G"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health-check
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
      imagePullSecrets:
        - name: regsecret
      volumes:
        - name: youtube-persistent-storage
          persistentVolumeClaim:
            claimName: youtube-persistent-storage
