apiVersion: v1
kind: Service
metadata:
  name: {{ include "youtube.fullname" . }}-service
  labels:
    app: {{ include "youtube.fullname" . }}
  {{- include "youtube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "youtube.fullname" . }}
  {{- include "youtube.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}